import { styled, keyframes } from "@styles/global";

import { DECORATIONS_HEADER_HEIGHT } from "@components/Decorations/styles";
import { color } from "./theme";

export const Content = styled("div", {
	display: "flex",
	position: "relative",
	flexDirection: "row",

	backgroundColor: color("bgCentral"),
	marginTop: DECORATIONS_HEADER_HEIGHT,
});

const ripple = keyframes({
	"0%": {
		top: 36,
		left: 36,
		width: 0,
		height: 0,
		opacity: 1,
	},
	"100%": {
		top: 0,
		left: 0,
		width: 72,
		height: 72,
		opacity: 0,
	},
});

const AnimStyle = styled("div", {
	// generated by https://loading.io/

	marginLeft: -48,

	"&.lds-ripple": {
		display: "inline-block",
		position: "relative",
		height: 80,
		width: 80,
	},

	"&.lds-ripple div": {
		position: "absolute",
		border: `3px solid ${color("accent")}`,
		borderRadius: "50%",
		opacity: 1,

		animation: `${ripple} 1.3s cubic-bezier(0, 0.2, 0.8, 1) infinite`,
	},

	"&.lds-ripple div:nth-of-type(2)": {
		animationDelay: "-0.5s",
	},
});

export const Loading = () => (
	<AnimStyle>
		<div className="lds-ripple">
			<div></div>
			<div></div>
		</div>
	</AnimStyle>
);

// --dark-button-shadow:
// 			-2px -2px 4px rgba(255, 255, 255, 0.05),
// 			0 0 10px 10px rgba(255, 255, 255, 0.005),
// 			2px 2px 8px rgba(60, 60, 60, 0.1);
