import styled from "@emotion/styled";

import { theme } from "./theme";

export const MainView = styled.div`
	display: flex;
	position: relative;
	flex-direction: row;

	background-color: ${theme.colors.bgCentral};
`;

const AnimStyle = styled.div`
	margin-left: -48px;

	.lds-ripple {
		display: inline-block;
		position: relative;
		width: 80px;
		height: 80px;
	}

	.lds-ripple div {
		position: absolute;
		border: 3px solid ${theme.colors.accent};
		opacity: 1;
		border-radius: 50%;
		animation: ripple 1.3s cubic-bezier(0, 0.2, 0.8, 1) infinite;
	}

	.lds-ripple div:nth-of-type(2) {
		animation-delay: -0.5s;
	}

	@keyframes ripple {
		0% {
			top: 36px;
			left: 36px;
			width: 0;
			height: 0;
			opacity: 1;
		}
		100% {
			top: 0px;
			left: 0px;
			width: 72px;
			height: 72px;
			opacity: 0;
		}
	}

	/* generated by https://loading.io/ */
`;

export const Loading = () => (
	<AnimStyle>
		<div className="lds-ripple">
			<div></div>
			<div></div>
		</div>
	</AnimStyle>
);

// --dark-button-shadow:
// 			-2px -2px 4px rgba(255, 255, 255, 0.05),
// 			0 0 10px 10px rgba(255, 255, 255, 0.005),
// 			2px 2px 8px rgba(60, 60, 60, 0.1);
