import { DECORATIONS_HEADER_HEIGHT } from "@components/Decorations/styles";
import { styled, keyframes } from "@styles/global";

export const Content = styled("div", {
	display: "grid",
	gridTemplate: `
		"nav main-area media-player" 100%
		/ 65px 1fr minmax(186px, 25vw)
	`,

	marginTop: DECORATIONS_HEADER_HEIGHT,
	backgroundColor: "$bg-main",

	"@sm": {
		gridTemplate: `
		"nav main-area" 1fr
		/ 35px 1fr
		"media-player" 70px
		/ 1fr
	`,
	},
});

const ripple = keyframes({
	"0%": {
		top: 36,
		left: 36,
		width: 0,
		height: 0,
		opacity: 1,
	},
	"100%": {
		top: 0,
		left: 0,
		width: 72,
		height: 72,
		opacity: 0,
	},
});

const AnimStyle = styled("div", {
	// generated by https://loading.io/

	marginLeft: -48,

	"&.lds-ripple": {
		display: "inline-block",
		position: "relative",
		height: 80,
		width: 80,
	},

	"&.lds-ripple div": {
		position: "absolute",

		border: "3px solid $accent",
		borderRadius: "50%",
		opacity: 1,

		animation: `${ripple} 1.3s cubic-bezier(0, 0.2, 0.8, 1) infinite`,
	},

	"&.lds-ripple div:nth-of-type(2)": {
		animationDelay: "-0.5s",
	},
});

const rotating = keyframes({
	to: {
		transform: "rotate(1turn)",
	},
});

export const Loading = styled("div", {
	animation: `${rotating} 1s infinite`,
	border: "6px solid #e5e5e5",
	borderTopColor: "#51d4db",
	borderRadius: "50%",
	size: 50,
});

// export const Loading = () => (
// 	<AnimStyle>
// 		<div className="lds-ripple">
// 			<div></div>
// 			<div></div>
// 		</div>
// 	</AnimStyle>
// );
