export const theme = {
	colors: {
		navButtonHoveredColor: "var(--nav-button-hovered-color)",
		navButtonActiveColor: "var(--nav-button-active-color)",
		navButtonHoveredBg: "var(--nav-button-hovered-bg)",
		navButtonActiveBg: "var(--nav-button-active-bg)",
		deactivatedIcon: "var(--deactivated-icon)",
		buttonHovered: "var(--button-hovered)",
		buttonBorder: "var(--button-border)",
		accentAlpha: "var(--accent-alpha)",
		accentLight: "var(--accent-light)",
		activeIcon: "var(--active-icon)",
		bgCentral: "var(--bg-central)",
		blackText: "var(--black-text)",
		boxShadow: "var(--box-shadow)",
		secondary: "var(--secondary)",
		grayText: "var(--gray-text)",
		primary: "var(--primary)",
		accent: "var(--accent)",
		bgNav: "var(--bg-nav)",
		text: "var(--text)",
	},
} as const;
