name: Build and release

on:
  push:
    branches:
      # this will run on the 'build' branch
      - build

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 16.5.0
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Show directory
        run: ls

      - name: Build AppImage
        run: yarn release

      - name: Show directory of build
        run: ls dist

      # Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        env:
          # This token is provided by Actions, you do not need to create your own token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          draft: true # Mark this release as draft (not real)
          files: dist/Muse-*
