name: Build and release

on:
  push:
    branches:
      # this will run on the 'build' branch
      - build

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 16.5.0
          cache: yarn

      - name: Setup yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn

      - name: Show directory
        run: ls

      - name: Build AppImage
        run: yarn release

      - name: Show directory of build
        run: ls dist

      # Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          # This token is provided by Actions, you do not need to create your own token
          files: ["dist/Muse-*", "latest-linux.yml"]
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          draft: false # Mark this release as draft (not real)
