# To make this file run, do this on the terminal:

# Make sure your working tree is in a clean state:
# > git status

# Check out to the `build` branch:
# > git checkout build

# Reset that branch to some other branch/commit:
# > git reset --hard main

name: Build and release

on:
  push:
    branches:
      - build

jobs:
  build_on_linux:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 16.5.0
          cache: yarn

      - name: Setup yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn

      - name: Show directory
        run: ls

      - name: Build AppImage
        run: yarn release

      - name: Show directory of build
        run: ls dist

      - name: Show directory
        run: ls

      - name: Move files
        run: |
          mv dist/latest-linux.yml .
          mv dist/Muse-* .

      - name: Show directory
        run: ls

      - name: Release action
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          # This token is provided by Actions, you do not need to create your own token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          files: |
            "latest-linux.yml"
            "Muse-*"
            *
