name: Run tests on every push

on:
  push:
    branches:
      - "**" # matches every branch

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: 'yarn'

      - name: Print yarn cache folder and it's size
        run: |
          ls /home/runner/.cache/yarn/v6
          du -sh /home/runner/.cache/yarn/v6

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test --run # do not watch

