name: Run tests on every push

on:
  push:
    branches:
      - "**" # matches every branch

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS, checkout code, install dependencies and run tests
        # Checkout code:
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # Setup NodeJS:
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: 'yarn'
        # Install dependencies:
        run: yarn
        # Run tests:
        run: yarn test --run # do not watch

